# General Project Settings
project:
  name: Chatbot-Restaurant
  version: 1.0.0
  description: A chatbot designed for restaurant customer service in Saudi Arabia.

# Database Configuration
database:
  type: sqlite
  path: "/workspaces/Chatbot-Restaurant/database/restaurant.db"
  FAQsQ: "SELECT * FROM faqs;"
  columns_faqs: ['question', 'answer']
  MENUITEMsQ: "SELECT * FROM menu_items;"
  columns_menuitems: ['name', 'price', 'description', 'ingredients', 'allergens'] 

# Retrieval System Configuration
retrieval:
  top_k_results: 2  # Number of results to return per query

# Generative Model Configuration
generative_model:
  max_length: 200
  do_sample: True
  temperature: 0.99
  top_k: 60
  top_p: 0.99

# API Configuration
api:
  host: 127.0.0.1
  port: 8000
  debug: true
  timeout: 60  # seconds